### ISSUE TITLE
Project 2 Feedback

### ISSUE THREAD

**Issue by Avizacherman** [sticknanton/restaurantapp#2]
Nick,

Good job on your project. The UI is intuitive and clean, I like that you seperate the kitchen and bar, and you also can split checks. Nice little touches. I didn't see a way to convert to Euros though? Am I missing this? 

Your code is pretty clean too. One thing I did notice that stuck out was in your tests, you have the following:

``` rb
    describe '#favorite_candy' do
      it 'returns Total cost' do
        actual = @party.total()
        expectation = 11.00
        expect(actual).to eq(expectation)
      end
    end

```

What's the favorite_candy method? 

Overall pretty good job.

**Comment by sticknanton** [comment]
favorite_candy is a definite typo lol

**Comment by sticknanton** [comment]
That conversion is actually missing at the moment, I think I made the mistake of thinking that was optional..? If not I can probably find the time to implement that this weekend.

**Comment by Avizacherman** [comment]
Score: 2 out of 3.
